server:
  port: 8888
  servlet:
    context-path: /plus
spring:
  #使用默认的数据源Hikari
  #mysql6以上的都需要使用com.mysql.cj.jdbc.Driver,还需要指定时区serverTimezone
  datasource:
    url: jdbc:mysql://localhost:3306/security_db?useUnicode=true&autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #指定数据源类型
    type: com.zaxxer.hikari.HikariDataSource

    #hikari配置
    hikari:
      #最小空闲连接数量
      minimum-idle: 5
      #最大空闲连接存活时间，默认是600000（10分钟）
      idle-timeout: 18000
      #连接池最大连接数，默认是10
      maximum-pool-size: 15
      #此属性控制从池返回的连接的默认自动提交行为，默认值为true(自动提交从池中返回的连接)
      auto-commit: true
      #连接池中连接的最长生命周期，值为0表示无限生命周期，默认1800000，即30分钟
      max-lifetime: 1800000
      #数据库连接超时时间，默认是30秒
      connection-test-query: SELECT 1
      #等待来自池的连接的最大毫秒数
      connection-timeout: 30000


