server:
  port: 8080
  servlet:
    context-path: /
spring:
  thymeleaf:
    #开发时禁用缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taco_cloud?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    password: 62216991gsy
    username: root

